/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Additional non-threat content verification information
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T08:41:21.483351Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class AdditionalAdvancedScanInformation {
  public static final String SERIALIZED_NAME_CONTAINS_J_S_O_N = "ContainsJSON";
  @SerializedName(SERIALIZED_NAME_CONTAINS_J_S_O_N)
  @javax.annotation.Nullable
  private Boolean containsJSON;

  public static final String SERIALIZED_NAME_CONTAINS_X_M_L = "ContainsXML";
  @SerializedName(SERIALIZED_NAME_CONTAINS_X_M_L)
  @javax.annotation.Nullable
  private Boolean containsXML;

  public static final String SERIALIZED_NAME_CONTAINS_IMAGE = "ContainsImage";
  @SerializedName(SERIALIZED_NAME_CONTAINS_IMAGE)
  @javax.annotation.Nullable
  private Boolean containsImage;

  public static final String SERIALIZED_NAME_HASH_S_H_A1 = "Hash_SHA1";
  @SerializedName(SERIALIZED_NAME_HASH_S_H_A1)
  @javax.annotation.Nullable
  private String hashSHA1;

  public static final String SERIALIZED_NAME_RELEVANT_SUBFILE_NAME = "RelevantSubfileName";
  @SerializedName(SERIALIZED_NAME_RELEVANT_SUBFILE_NAME)
  @javax.annotation.Nullable
  private String relevantSubfileName;

  public static final String SERIALIZED_NAME_RELEVANT_SUBFILE_HASH_S_H_A1 = "RelevantSubfileHash_SHA1";
  @SerializedName(SERIALIZED_NAME_RELEVANT_SUBFILE_HASH_S_H_A1)
  @javax.annotation.Nullable
  private String relevantSubfileHashSHA1;

  public static final String SERIALIZED_NAME_IS_AUTHENTICODE_SIGNED = "IsAuthenticodeSigned";
  @SerializedName(SERIALIZED_NAME_IS_AUTHENTICODE_SIGNED)
  @javax.annotation.Nullable
  private Boolean isAuthenticodeSigned;

  public AdditionalAdvancedScanInformation() {
  }

  public AdditionalAdvancedScanInformation containsJSON(@javax.annotation.Nullable Boolean containsJSON) {
    this.containsJSON = containsJSON;
    return this;
  }

  /**
   * True if the input file contains JSON data, false otherwise; this is not a threat signal
   * @return containsJSON
   */
  @javax.annotation.Nullable
  public Boolean getContainsJSON() {
    return containsJSON;
  }

  public void setContainsJSON(@javax.annotation.Nullable Boolean containsJSON) {
    this.containsJSON = containsJSON;
  }


  public AdditionalAdvancedScanInformation containsXML(@javax.annotation.Nullable Boolean containsXML) {
    this.containsXML = containsXML;
    return this;
  }

  /**
   * True if the input file contains XML data, false otherwise; this is not a threat signal
   * @return containsXML
   */
  @javax.annotation.Nullable
  public Boolean getContainsXML() {
    return containsXML;
  }

  public void setContainsXML(@javax.annotation.Nullable Boolean containsXML) {
    this.containsXML = containsXML;
  }


  public AdditionalAdvancedScanInformation containsImage(@javax.annotation.Nullable Boolean containsImage) {
    this.containsImage = containsImage;
    return this;
  }

  /**
   * True if the input file contains an image
   * @return containsImage
   */
  @javax.annotation.Nullable
  public Boolean getContainsImage() {
    return containsImage;
  }

  public void setContainsImage(@javax.annotation.Nullable Boolean containsImage) {
    this.containsImage = containsImage;
  }


  public AdditionalAdvancedScanInformation hashSHA1(@javax.annotation.Nullable String hashSHA1) {
    this.hashSHA1 = hashSHA1;
    return this;
  }

  /**
   * SHA1 hash of input file
   * @return hashSHA1
   */
  @javax.annotation.Nullable
  public String getHashSHA1() {
    return hashSHA1;
  }

  public void setHashSHA1(@javax.annotation.Nullable String hashSHA1) {
    this.hashSHA1 = hashSHA1;
  }


  public AdditionalAdvancedScanInformation relevantSubfileName(@javax.annotation.Nullable String relevantSubfileName) {
    this.relevantSubfileName = relevantSubfileName;
    return this;
  }

  /**
   * Relevant subfile name in an archive format for identified threats, if any
   * @return relevantSubfileName
   */
  @javax.annotation.Nullable
  public String getRelevantSubfileName() {
    return relevantSubfileName;
  }

  public void setRelevantSubfileName(@javax.annotation.Nullable String relevantSubfileName) {
    this.relevantSubfileName = relevantSubfileName;
  }


  public AdditionalAdvancedScanInformation relevantSubfileHashSHA1(@javax.annotation.Nullable String relevantSubfileHashSHA1) {
    this.relevantSubfileHashSHA1 = relevantSubfileHashSHA1;
    return this;
  }

  /**
   * SHA1 hash of relevant subfile name in an archive format for identified threats, if any
   * @return relevantSubfileHashSHA1
   */
  @javax.annotation.Nullable
  public String getRelevantSubfileHashSHA1() {
    return relevantSubfileHashSHA1;
  }

  public void setRelevantSubfileHashSHA1(@javax.annotation.Nullable String relevantSubfileHashSHA1) {
    this.relevantSubfileHashSHA1 = relevantSubfileHashSHA1;
  }


  public AdditionalAdvancedScanInformation isAuthenticodeSigned(@javax.annotation.Nullable Boolean isAuthenticodeSigned) {
    this.isAuthenticodeSigned = isAuthenticodeSigned;
    return this;
  }

  /**
   * True if there is a valid Authenticode signature, False otherwise
   * @return isAuthenticodeSigned
   */
  @javax.annotation.Nullable
  public Boolean getIsAuthenticodeSigned() {
    return isAuthenticodeSigned;
  }

  public void setIsAuthenticodeSigned(@javax.annotation.Nullable Boolean isAuthenticodeSigned) {
    this.isAuthenticodeSigned = isAuthenticodeSigned;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalAdvancedScanInformation additionalAdvancedScanInformation = (AdditionalAdvancedScanInformation) o;
    return Objects.equals(this.containsJSON, additionalAdvancedScanInformation.containsJSON) &&
        Objects.equals(this.containsXML, additionalAdvancedScanInformation.containsXML) &&
        Objects.equals(this.containsImage, additionalAdvancedScanInformation.containsImage) &&
        Objects.equals(this.hashSHA1, additionalAdvancedScanInformation.hashSHA1) &&
        Objects.equals(this.relevantSubfileName, additionalAdvancedScanInformation.relevantSubfileName) &&
        Objects.equals(this.relevantSubfileHashSHA1, additionalAdvancedScanInformation.relevantSubfileHashSHA1) &&
        Objects.equals(this.isAuthenticodeSigned, additionalAdvancedScanInformation.isAuthenticodeSigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containsJSON, containsXML, containsImage, hashSHA1, relevantSubfileName, relevantSubfileHashSHA1, isAuthenticodeSigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalAdvancedScanInformation {\n");
    sb.append("    containsJSON: ").append(toIndentedString(containsJSON)).append("\n");
    sb.append("    containsXML: ").append(toIndentedString(containsXML)).append("\n");
    sb.append("    containsImage: ").append(toIndentedString(containsImage)).append("\n");
    sb.append("    hashSHA1: ").append(toIndentedString(hashSHA1)).append("\n");
    sb.append("    relevantSubfileName: ").append(toIndentedString(relevantSubfileName)).append("\n");
    sb.append("    relevantSubfileHashSHA1: ").append(toIndentedString(relevantSubfileHashSHA1)).append("\n");
    sb.append("    isAuthenticodeSigned: ").append(toIndentedString(isAuthenticodeSigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ContainsJSON");
    openapiFields.add("ContainsXML");
    openapiFields.add("ContainsImage");
    openapiFields.add("Hash_SHA1");
    openapiFields.add("RelevantSubfileName");
    openapiFields.add("RelevantSubfileHash_SHA1");
    openapiFields.add("IsAuthenticodeSigned");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdditionalAdvancedScanInformation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdditionalAdvancedScanInformation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdditionalAdvancedScanInformation is not found in the empty JSON string", AdditionalAdvancedScanInformation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdditionalAdvancedScanInformation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AdditionalAdvancedScanInformation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Hash_SHA1") != null && !jsonObj.get("Hash_SHA1").isJsonNull()) && !jsonObj.get("Hash_SHA1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Hash_SHA1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Hash_SHA1").toString()));
      }
      if ((jsonObj.get("RelevantSubfileName") != null && !jsonObj.get("RelevantSubfileName").isJsonNull()) && !jsonObj.get("RelevantSubfileName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RelevantSubfileName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RelevantSubfileName").toString()));
      }
      if ((jsonObj.get("RelevantSubfileHash_SHA1") != null && !jsonObj.get("RelevantSubfileHash_SHA1").isJsonNull()) && !jsonObj.get("RelevantSubfileHash_SHA1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RelevantSubfileHash_SHA1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RelevantSubfileHash_SHA1").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdditionalAdvancedScanInformation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdditionalAdvancedScanInformation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdditionalAdvancedScanInformation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdditionalAdvancedScanInformation.class));

       return (TypeAdapter<T>) new TypeAdapter<AdditionalAdvancedScanInformation>() {
           @Override
           public void write(JsonWriter out, AdditionalAdvancedScanInformation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdditionalAdvancedScanInformation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdditionalAdvancedScanInformation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdditionalAdvancedScanInformation
   * @throws IOException if the JSON string is invalid with respect to AdditionalAdvancedScanInformation
   */
  public static AdditionalAdvancedScanInformation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdditionalAdvancedScanInformation.class);
  }

  /**
   * Convert an instance of AdditionalAdvancedScanInformation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

