/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CloudStorageAdvancedVirusScanResult;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Status of the scan cloud storage job
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T23:59:36.607801Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class ScanCloudStorageJobStatusResult {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "Successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String SERIALIZED_NAME_ASYNC_JOB_STATUS = "AsyncJobStatus";
  @SerializedName(SERIALIZED_NAME_ASYNC_JOB_STATUS)
  @javax.annotation.Nullable
  private String asyncJobStatus;

  public static final String SERIALIZED_NAME_ASYNC_JOB_I_D = "AsyncJobID";
  @SerializedName(SERIALIZED_NAME_ASYNC_JOB_I_D)
  @javax.annotation.Nullable
  private String asyncJobID;

  public static final String SERIALIZED_NAME_RESULT = "Result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  @javax.annotation.Nullable
  private CloudStorageAdvancedVirusScanResult result;

  public static final String SERIALIZED_NAME_JOB_DURATION = "JobDuration";
  @SerializedName(SERIALIZED_NAME_JOB_DURATION)
  @javax.annotation.Nullable
  private String jobDuration;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "ErrorMessage";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public ScanCloudStorageJobStatusResult() {
  }

  public ScanCloudStorageJobStatusResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * Tru eif the operation to check the status of the job was successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public ScanCloudStorageJobStatusResult asyncJobStatus(@javax.annotation.Nullable String asyncJobStatus) {
    this.asyncJobStatus = asyncJobStatus;
    return this;
  }

  /**
   * Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
   * @return asyncJobStatus
   */
  @javax.annotation.Nullable
  public String getAsyncJobStatus() {
    return asyncJobStatus;
  }

  public void setAsyncJobStatus(@javax.annotation.Nullable String asyncJobStatus) {
    this.asyncJobStatus = asyncJobStatus;
  }


  public ScanCloudStorageJobStatusResult asyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
    return this;
  }

  /**
   * Job ID of the async batch job
   * @return asyncJobID
   */
  @javax.annotation.Nullable
  public String getAsyncJobID() {
    return asyncJobID;
  }

  public void setAsyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
  }


  public ScanCloudStorageJobStatusResult result(@javax.annotation.Nullable CloudStorageAdvancedVirusScanResult result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nullable
  public CloudStorageAdvancedVirusScanResult getResult() {
    return result;
  }

  public void setResult(@javax.annotation.Nullable CloudStorageAdvancedVirusScanResult result) {
    this.result = result;
  }


  public ScanCloudStorageJobStatusResult jobDuration(@javax.annotation.Nullable String jobDuration) {
    this.jobDuration = jobDuration;
    return this;
  }

  /**
   * Duration of a completed job
   * @return jobDuration
   */
  @javax.annotation.Nullable
  public String getJobDuration() {
    return jobDuration;
  }

  public void setJobDuration(@javax.annotation.Nullable String jobDuration) {
    this.jobDuration = jobDuration;
  }


  public ScanCloudStorageJobStatusResult errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Error message (if any)
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanCloudStorageJobStatusResult scanCloudStorageJobStatusResult = (ScanCloudStorageJobStatusResult) o;
    return Objects.equals(this.successful, scanCloudStorageJobStatusResult.successful) &&
        Objects.equals(this.asyncJobStatus, scanCloudStorageJobStatusResult.asyncJobStatus) &&
        Objects.equals(this.asyncJobID, scanCloudStorageJobStatusResult.asyncJobID) &&
        Objects.equals(this.result, scanCloudStorageJobStatusResult.result) &&
        Objects.equals(this.jobDuration, scanCloudStorageJobStatusResult.jobDuration) &&
        Objects.equals(this.errorMessage, scanCloudStorageJobStatusResult.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, asyncJobStatus, asyncJobID, result, jobDuration, errorMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanCloudStorageJobStatusResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    asyncJobStatus: ").append(toIndentedString(asyncJobStatus)).append("\n");
    sb.append("    asyncJobID: ").append(toIndentedString(asyncJobID)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    jobDuration: ").append(toIndentedString(jobDuration)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Successful");
    openapiFields.add("AsyncJobStatus");
    openapiFields.add("AsyncJobID");
    openapiFields.add("Result");
    openapiFields.add("JobDuration");
    openapiFields.add("ErrorMessage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScanCloudStorageJobStatusResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScanCloudStorageJobStatusResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScanCloudStorageJobStatusResult is not found in the empty JSON string", ScanCloudStorageJobStatusResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScanCloudStorageJobStatusResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScanCloudStorageJobStatusResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AsyncJobStatus") != null && !jsonObj.get("AsyncJobStatus").isJsonNull()) && !jsonObj.get("AsyncJobStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AsyncJobStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AsyncJobStatus").toString()));
      }
      if ((jsonObj.get("AsyncJobID") != null && !jsonObj.get("AsyncJobID").isJsonNull()) && !jsonObj.get("AsyncJobID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AsyncJobID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AsyncJobID").toString()));
      }
      // validate the optional field `Result`
      if (jsonObj.get("Result") != null && !jsonObj.get("Result").isJsonNull()) {
        CloudStorageAdvancedVirusScanResult.validateJsonElement(jsonObj.get("Result"));
      }
      if ((jsonObj.get("JobDuration") != null && !jsonObj.get("JobDuration").isJsonNull()) && !jsonObj.get("JobDuration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `JobDuration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("JobDuration").toString()));
      }
      if ((jsonObj.get("ErrorMessage") != null && !jsonObj.get("ErrorMessage").isJsonNull()) && !jsonObj.get("ErrorMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ErrorMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ErrorMessage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScanCloudStorageJobStatusResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScanCloudStorageJobStatusResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScanCloudStorageJobStatusResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScanCloudStorageJobStatusResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ScanCloudStorageJobStatusResult>() {
           @Override
           public void write(JsonWriter out, ScanCloudStorageJobStatusResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScanCloudStorageJobStatusResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScanCloudStorageJobStatusResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScanCloudStorageJobStatusResult
   * @throws IOException if the JSON string is invalid with respect to ScanCloudStorageJobStatusResult
   */
  public static ScanCloudStorageJobStatusResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScanCloudStorageJobStatusResult.class);
  }

  /**
   * Convert an instance of ScanCloudStorageJobStatusResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

