/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of performing a convert documentbatch job operation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T08:41:21.483351Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class ScanCloudStorageBatchJobCreateResult {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "Successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String SERIALIZED_NAME_ASYNC_JOB_I_D = "AsyncJobID";
  @SerializedName(SERIALIZED_NAME_ASYNC_JOB_I_D)
  @javax.annotation.Nullable
  private String asyncJobID;

  public ScanCloudStorageBatchJobCreateResult() {
  }

  public ScanCloudStorageBatchJobCreateResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public ScanCloudStorageBatchJobCreateResult asyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
    return this;
  }

  /**
   * When creating a job, an Async Job ID is returned.  Use the GetAsyncJobStatus API to check on the status of this job using the AsyncJobID and get the result when it finishes
   * @return asyncJobID
   */
  @javax.annotation.Nullable
  public String getAsyncJobID() {
    return asyncJobID;
  }

  public void setAsyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanCloudStorageBatchJobCreateResult scanCloudStorageBatchJobCreateResult = (ScanCloudStorageBatchJobCreateResult) o;
    return Objects.equals(this.successful, scanCloudStorageBatchJobCreateResult.successful) &&
        Objects.equals(this.asyncJobID, scanCloudStorageBatchJobCreateResult.asyncJobID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, asyncJobID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanCloudStorageBatchJobCreateResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    asyncJobID: ").append(toIndentedString(asyncJobID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Successful");
    openapiFields.add("AsyncJobID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScanCloudStorageBatchJobCreateResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScanCloudStorageBatchJobCreateResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScanCloudStorageBatchJobCreateResult is not found in the empty JSON string", ScanCloudStorageBatchJobCreateResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScanCloudStorageBatchJobCreateResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScanCloudStorageBatchJobCreateResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AsyncJobID") != null && !jsonObj.get("AsyncJobID").isJsonNull()) && !jsonObj.get("AsyncJobID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AsyncJobID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AsyncJobID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScanCloudStorageBatchJobCreateResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScanCloudStorageBatchJobCreateResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScanCloudStorageBatchJobCreateResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScanCloudStorageBatchJobCreateResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ScanCloudStorageBatchJobCreateResult>() {
           @Override
           public void write(JsonWriter out, ScanCloudStorageBatchJobCreateResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScanCloudStorageBatchJobCreateResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScanCloudStorageBatchJobCreateResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScanCloudStorageBatchJobCreateResult
   * @throws IOException if the JSON string is invalid with respect to ScanCloudStorageBatchJobCreateResult
   */
  public static ScanCloudStorageBatchJobCreateResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScanCloudStorageBatchJobCreateResult.class);
  }

  /**
   * Convert an instance of ScanCloudStorageBatchJobCreateResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

