/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AdditionalAdvancedScanInformation;
import org.openapitools.client.model.VirusFound;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of running an advanced virus scan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T08:41:21.483351Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class VirusScanAdvancedResult {
  public static final String SERIALIZED_NAME_CLEAN_RESULT = "CleanResult";
  @SerializedName(SERIALIZED_NAME_CLEAN_RESULT)
  @javax.annotation.Nullable
  private Boolean cleanResult;

  public static final String SERIALIZED_NAME_CONTAINS_EXECUTABLE = "ContainsExecutable";
  @SerializedName(SERIALIZED_NAME_CONTAINS_EXECUTABLE)
  @javax.annotation.Nullable
  private Boolean containsExecutable;

  public static final String SERIALIZED_NAME_CONTAINS_INVALID_FILE = "ContainsInvalidFile";
  @SerializedName(SERIALIZED_NAME_CONTAINS_INVALID_FILE)
  @javax.annotation.Nullable
  private Boolean containsInvalidFile;

  public static final String SERIALIZED_NAME_CONTAINS_SCRIPT = "ContainsScript";
  @SerializedName(SERIALIZED_NAME_CONTAINS_SCRIPT)
  @javax.annotation.Nullable
  private Boolean containsScript;

  public static final String SERIALIZED_NAME_CONTAINS_PASSWORD_PROTECTED_FILE = "ContainsPasswordProtectedFile";
  @SerializedName(SERIALIZED_NAME_CONTAINS_PASSWORD_PROTECTED_FILE)
  @javax.annotation.Nullable
  private Boolean containsPasswordProtectedFile;

  public static final String SERIALIZED_NAME_CONTAINS_RESTRICTED_FILE_FORMAT = "ContainsRestrictedFileFormat";
  @SerializedName(SERIALIZED_NAME_CONTAINS_RESTRICTED_FILE_FORMAT)
  @javax.annotation.Nullable
  private Boolean containsRestrictedFileFormat;

  public static final String SERIALIZED_NAME_CONTAINS_MACROS = "ContainsMacros";
  @SerializedName(SERIALIZED_NAME_CONTAINS_MACROS)
  @javax.annotation.Nullable
  private Boolean containsMacros;

  public static final String SERIALIZED_NAME_CONTAINS_XML_EXTERNAL_ENTITIES = "ContainsXmlExternalEntities";
  @SerializedName(SERIALIZED_NAME_CONTAINS_XML_EXTERNAL_ENTITIES)
  @javax.annotation.Nullable
  private Boolean containsXmlExternalEntities;

  public static final String SERIALIZED_NAME_CONTAINS_INSECURE_DESERIALIZATION = "ContainsInsecureDeserialization";
  @SerializedName(SERIALIZED_NAME_CONTAINS_INSECURE_DESERIALIZATION)
  @javax.annotation.Nullable
  private Boolean containsInsecureDeserialization;

  public static final String SERIALIZED_NAME_CONTAINS_HTML = "ContainsHtml";
  @SerializedName(SERIALIZED_NAME_CONTAINS_HTML)
  @javax.annotation.Nullable
  private Boolean containsHtml;

  public static final String SERIALIZED_NAME_CONTAINS_UNSAFE_ARCHIVE = "ContainsUnsafeArchive";
  @SerializedName(SERIALIZED_NAME_CONTAINS_UNSAFE_ARCHIVE)
  @javax.annotation.Nullable
  private Boolean containsUnsafeArchive;

  public static final String SERIALIZED_NAME_CONTAINS_OLE_EMBEDDED_OBJECT = "ContainsOleEmbeddedObject";
  @SerializedName(SERIALIZED_NAME_CONTAINS_OLE_EMBEDDED_OBJECT)
  @javax.annotation.Nullable
  private Boolean containsOleEmbeddedObject;

  public static final String SERIALIZED_NAME_CONTAINS_UNWANTED_ACTION = "ContainsUnwantedAction";
  @SerializedName(SERIALIZED_NAME_CONTAINS_UNWANTED_ACTION)
  @javax.annotation.Nullable
  private Boolean containsUnwantedAction;

  public static final String SERIALIZED_NAME_VERIFIED_FILE_FORMAT = "VerifiedFileFormat";
  @SerializedName(SERIALIZED_NAME_VERIFIED_FILE_FORMAT)
  @javax.annotation.Nullable
  private String verifiedFileFormat;

  public static final String SERIALIZED_NAME_FOUND_VIRUSES = "FoundViruses";
  @SerializedName(SERIALIZED_NAME_FOUND_VIRUSES)
  @javax.annotation.Nullable
  private List<VirusFound> foundViruses = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONTENT_INFORMATION = "ContentInformation";
  @SerializedName(SERIALIZED_NAME_CONTENT_INFORMATION)
  @javax.annotation.Nullable
  private AdditionalAdvancedScanInformation contentInformation;

  public VirusScanAdvancedResult() {
  }

  public VirusScanAdvancedResult cleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
    return this;
  }

  /**
   * True if the scan contained no viruses, false otherwise
   * @return cleanResult
   */
  @javax.annotation.Nullable
  public Boolean getCleanResult() {
    return cleanResult;
  }

  public void setCleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
  }


  public VirusScanAdvancedResult containsExecutable(@javax.annotation.Nullable Boolean containsExecutable) {
    this.containsExecutable = containsExecutable;
    return this;
  }

  /**
   * True if the scan contained an executable (application code), which can be a significant risk factor
   * @return containsExecutable
   */
  @javax.annotation.Nullable
  public Boolean getContainsExecutable() {
    return containsExecutable;
  }

  public void setContainsExecutable(@javax.annotation.Nullable Boolean containsExecutable) {
    this.containsExecutable = containsExecutable;
  }


  public VirusScanAdvancedResult containsInvalidFile(@javax.annotation.Nullable Boolean containsInvalidFile) {
    this.containsInvalidFile = containsInvalidFile;
    return this;
  }

  /**
   * True if the scan contained an invalid file (such as a PDF that is not a valid PDF, Word Document that is not a valid Word Document, etc.), which can be a significant risk factor
   * @return containsInvalidFile
   */
  @javax.annotation.Nullable
  public Boolean getContainsInvalidFile() {
    return containsInvalidFile;
  }

  public void setContainsInvalidFile(@javax.annotation.Nullable Boolean containsInvalidFile) {
    this.containsInvalidFile = containsInvalidFile;
  }


  public VirusScanAdvancedResult containsScript(@javax.annotation.Nullable Boolean containsScript) {
    this.containsScript = containsScript;
    return this;
  }

  /**
   * True if the scan contained a script (such as a PHP script, Python script, etc.) which can be a significant risk factor
   * @return containsScript
   */
  @javax.annotation.Nullable
  public Boolean getContainsScript() {
    return containsScript;
  }

  public void setContainsScript(@javax.annotation.Nullable Boolean containsScript) {
    this.containsScript = containsScript;
  }


  public VirusScanAdvancedResult containsPasswordProtectedFile(@javax.annotation.Nullable Boolean containsPasswordProtectedFile) {
    this.containsPasswordProtectedFile = containsPasswordProtectedFile;
    return this;
  }

  /**
   * True if the scan contained a password protected or encrypted file, which can be a significant risk factor
   * @return containsPasswordProtectedFile
   */
  @javax.annotation.Nullable
  public Boolean getContainsPasswordProtectedFile() {
    return containsPasswordProtectedFile;
  }

  public void setContainsPasswordProtectedFile(@javax.annotation.Nullable Boolean containsPasswordProtectedFile) {
    this.containsPasswordProtectedFile = containsPasswordProtectedFile;
  }


  public VirusScanAdvancedResult containsRestrictedFileFormat(@javax.annotation.Nullable Boolean containsRestrictedFileFormat) {
    this.containsRestrictedFileFormat = containsRestrictedFileFormat;
    return this;
  }

  /**
   * True if the uploaded file is of a type that is not allowed based on the optional restrictFileTypes parameter, false otherwise; if restrictFileTypes is not set, this will always be false
   * @return containsRestrictedFileFormat
   */
  @javax.annotation.Nullable
  public Boolean getContainsRestrictedFileFormat() {
    return containsRestrictedFileFormat;
  }

  public void setContainsRestrictedFileFormat(@javax.annotation.Nullable Boolean containsRestrictedFileFormat) {
    this.containsRestrictedFileFormat = containsRestrictedFileFormat;
  }


  public VirusScanAdvancedResult containsMacros(@javax.annotation.Nullable Boolean containsMacros) {
    this.containsMacros = containsMacros;
    return this;
  }

  /**
   * True if the uploaded file contains embedded Macros of other embedded threats within the document, which can be a significant risk factor
   * @return containsMacros
   */
  @javax.annotation.Nullable
  public Boolean getContainsMacros() {
    return containsMacros;
  }

  public void setContainsMacros(@javax.annotation.Nullable Boolean containsMacros) {
    this.containsMacros = containsMacros;
  }


  public VirusScanAdvancedResult containsXmlExternalEntities(@javax.annotation.Nullable Boolean containsXmlExternalEntities) {
    this.containsXmlExternalEntities = containsXmlExternalEntities;
    return this;
  }

  /**
   * True if the uploaded file contains embedded XML External Entity threats of other embedded threats within the document, which can be a significant risk factor
   * @return containsXmlExternalEntities
   */
  @javax.annotation.Nullable
  public Boolean getContainsXmlExternalEntities() {
    return containsXmlExternalEntities;
  }

  public void setContainsXmlExternalEntities(@javax.annotation.Nullable Boolean containsXmlExternalEntities) {
    this.containsXmlExternalEntities = containsXmlExternalEntities;
  }


  public VirusScanAdvancedResult containsInsecureDeserialization(@javax.annotation.Nullable Boolean containsInsecureDeserialization) {
    this.containsInsecureDeserialization = containsInsecureDeserialization;
    return this;
  }

  /**
   * True if the uploaded file contains embedded Insecure Deserialization threats of other embedded threats within the document, which can be a significant risk factor
   * @return containsInsecureDeserialization
   */
  @javax.annotation.Nullable
  public Boolean getContainsInsecureDeserialization() {
    return containsInsecureDeserialization;
  }

  public void setContainsInsecureDeserialization(@javax.annotation.Nullable Boolean containsInsecureDeserialization) {
    this.containsInsecureDeserialization = containsInsecureDeserialization;
  }


  public VirusScanAdvancedResult containsHtml(@javax.annotation.Nullable Boolean containsHtml) {
    this.containsHtml = containsHtml;
    return this;
  }

  /**
   * True if the uploaded file contains HTML, which can be a significant risk factor
   * @return containsHtml
   */
  @javax.annotation.Nullable
  public Boolean getContainsHtml() {
    return containsHtml;
  }

  public void setContainsHtml(@javax.annotation.Nullable Boolean containsHtml) {
    this.containsHtml = containsHtml;
  }


  public VirusScanAdvancedResult containsUnsafeArchive(@javax.annotation.Nullable Boolean containsUnsafeArchive) {
    this.containsUnsafeArchive = containsUnsafeArchive;
    return this;
  }

  /**
   * True if the uploaded file contains unsafe archive (e.g. zip) content, such as a Zip Bomb, or other configurations of a zip file that could lead to an unsafe extraction
   * @return containsUnsafeArchive
   */
  @javax.annotation.Nullable
  public Boolean getContainsUnsafeArchive() {
    return containsUnsafeArchive;
  }

  public void setContainsUnsafeArchive(@javax.annotation.Nullable Boolean containsUnsafeArchive) {
    this.containsUnsafeArchive = containsUnsafeArchive;
  }


  public VirusScanAdvancedResult containsOleEmbeddedObject(@javax.annotation.Nullable Boolean containsOleEmbeddedObject) {
    this.containsOleEmbeddedObject = containsOleEmbeddedObject;
    return this;
  }

  /**
   * True if the uploaded file contains an OLE embedded object, which can be a significant risk factor
   * @return containsOleEmbeddedObject
   */
  @javax.annotation.Nullable
  public Boolean getContainsOleEmbeddedObject() {
    return containsOleEmbeddedObject;
  }

  public void setContainsOleEmbeddedObject(@javax.annotation.Nullable Boolean containsOleEmbeddedObject) {
    this.containsOleEmbeddedObject = containsOleEmbeddedObject;
  }


  public VirusScanAdvancedResult containsUnwantedAction(@javax.annotation.Nullable Boolean containsUnwantedAction) {
    this.containsUnwantedAction = containsUnwantedAction;
    return this;
  }

  /**
   * True if the uploaded file contains an unwanted automatic action, which can be a significant risk factor
   * @return containsUnwantedAction
   */
  @javax.annotation.Nullable
  public Boolean getContainsUnwantedAction() {
    return containsUnwantedAction;
  }

  public void setContainsUnwantedAction(@javax.annotation.Nullable Boolean containsUnwantedAction) {
    this.containsUnwantedAction = containsUnwantedAction;
  }


  public VirusScanAdvancedResult verifiedFileFormat(@javax.annotation.Nullable String verifiedFileFormat) {
    this.verifiedFileFormat = verifiedFileFormat;
    return this;
  }

  /**
   * For file format verification-supported file formats, the contents-verified file format of the file.  Null indicates that the file format is not supported for contents verification.  If a Virus or Malware is found, this field will always be set to Null.
   * @return verifiedFileFormat
   */
  @javax.annotation.Nullable
  public String getVerifiedFileFormat() {
    return verifiedFileFormat;
  }

  public void setVerifiedFileFormat(@javax.annotation.Nullable String verifiedFileFormat) {
    this.verifiedFileFormat = verifiedFileFormat;
  }


  public VirusScanAdvancedResult foundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
    return this;
  }

  public VirusScanAdvancedResult addFoundVirusesItem(VirusFound foundVirusesItem) {
    if (this.foundViruses == null) {
      this.foundViruses = new ArrayList<>();
    }
    this.foundViruses.add(foundVirusesItem);
    return this;
  }

  /**
   * Array of viruses found, if any
   * @return foundViruses
   */
  @javax.annotation.Nullable
  public List<VirusFound> getFoundViruses() {
    return foundViruses;
  }

  public void setFoundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
  }


  public VirusScanAdvancedResult contentInformation(@javax.annotation.Nullable AdditionalAdvancedScanInformation contentInformation) {
    this.contentInformation = contentInformation;
    return this;
  }

  /**
   * Get contentInformation
   * @return contentInformation
   */
  @javax.annotation.Nullable
  public AdditionalAdvancedScanInformation getContentInformation() {
    return contentInformation;
  }

  public void setContentInformation(@javax.annotation.Nullable AdditionalAdvancedScanInformation contentInformation) {
    this.contentInformation = contentInformation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirusScanAdvancedResult virusScanAdvancedResult = (VirusScanAdvancedResult) o;
    return Objects.equals(this.cleanResult, virusScanAdvancedResult.cleanResult) &&
        Objects.equals(this.containsExecutable, virusScanAdvancedResult.containsExecutable) &&
        Objects.equals(this.containsInvalidFile, virusScanAdvancedResult.containsInvalidFile) &&
        Objects.equals(this.containsScript, virusScanAdvancedResult.containsScript) &&
        Objects.equals(this.containsPasswordProtectedFile, virusScanAdvancedResult.containsPasswordProtectedFile) &&
        Objects.equals(this.containsRestrictedFileFormat, virusScanAdvancedResult.containsRestrictedFileFormat) &&
        Objects.equals(this.containsMacros, virusScanAdvancedResult.containsMacros) &&
        Objects.equals(this.containsXmlExternalEntities, virusScanAdvancedResult.containsXmlExternalEntities) &&
        Objects.equals(this.containsInsecureDeserialization, virusScanAdvancedResult.containsInsecureDeserialization) &&
        Objects.equals(this.containsHtml, virusScanAdvancedResult.containsHtml) &&
        Objects.equals(this.containsUnsafeArchive, virusScanAdvancedResult.containsUnsafeArchive) &&
        Objects.equals(this.containsOleEmbeddedObject, virusScanAdvancedResult.containsOleEmbeddedObject) &&
        Objects.equals(this.containsUnwantedAction, virusScanAdvancedResult.containsUnwantedAction) &&
        Objects.equals(this.verifiedFileFormat, virusScanAdvancedResult.verifiedFileFormat) &&
        Objects.equals(this.foundViruses, virusScanAdvancedResult.foundViruses) &&
        Objects.equals(this.contentInformation, virusScanAdvancedResult.contentInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanResult, containsExecutable, containsInvalidFile, containsScript, containsPasswordProtectedFile, containsRestrictedFileFormat, containsMacros, containsXmlExternalEntities, containsInsecureDeserialization, containsHtml, containsUnsafeArchive, containsOleEmbeddedObject, containsUnwantedAction, verifiedFileFormat, foundViruses, contentInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirusScanAdvancedResult {\n");
    sb.append("    cleanResult: ").append(toIndentedString(cleanResult)).append("\n");
    sb.append("    containsExecutable: ").append(toIndentedString(containsExecutable)).append("\n");
    sb.append("    containsInvalidFile: ").append(toIndentedString(containsInvalidFile)).append("\n");
    sb.append("    containsScript: ").append(toIndentedString(containsScript)).append("\n");
    sb.append("    containsPasswordProtectedFile: ").append(toIndentedString(containsPasswordProtectedFile)).append("\n");
    sb.append("    containsRestrictedFileFormat: ").append(toIndentedString(containsRestrictedFileFormat)).append("\n");
    sb.append("    containsMacros: ").append(toIndentedString(containsMacros)).append("\n");
    sb.append("    containsXmlExternalEntities: ").append(toIndentedString(containsXmlExternalEntities)).append("\n");
    sb.append("    containsInsecureDeserialization: ").append(toIndentedString(containsInsecureDeserialization)).append("\n");
    sb.append("    containsHtml: ").append(toIndentedString(containsHtml)).append("\n");
    sb.append("    containsUnsafeArchive: ").append(toIndentedString(containsUnsafeArchive)).append("\n");
    sb.append("    containsOleEmbeddedObject: ").append(toIndentedString(containsOleEmbeddedObject)).append("\n");
    sb.append("    containsUnwantedAction: ").append(toIndentedString(containsUnwantedAction)).append("\n");
    sb.append("    verifiedFileFormat: ").append(toIndentedString(verifiedFileFormat)).append("\n");
    sb.append("    foundViruses: ").append(toIndentedString(foundViruses)).append("\n");
    sb.append("    contentInformation: ").append(toIndentedString(contentInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CleanResult");
    openapiFields.add("ContainsExecutable");
    openapiFields.add("ContainsInvalidFile");
    openapiFields.add("ContainsScript");
    openapiFields.add("ContainsPasswordProtectedFile");
    openapiFields.add("ContainsRestrictedFileFormat");
    openapiFields.add("ContainsMacros");
    openapiFields.add("ContainsXmlExternalEntities");
    openapiFields.add("ContainsInsecureDeserialization");
    openapiFields.add("ContainsHtml");
    openapiFields.add("ContainsUnsafeArchive");
    openapiFields.add("ContainsOleEmbeddedObject");
    openapiFields.add("ContainsUnwantedAction");
    openapiFields.add("VerifiedFileFormat");
    openapiFields.add("FoundViruses");
    openapiFields.add("ContentInformation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VirusScanAdvancedResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VirusScanAdvancedResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VirusScanAdvancedResult is not found in the empty JSON string", VirusScanAdvancedResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VirusScanAdvancedResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VirusScanAdvancedResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("VerifiedFileFormat") != null && !jsonObj.get("VerifiedFileFormat").isJsonNull()) && !jsonObj.get("VerifiedFileFormat").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `VerifiedFileFormat` to be a primitive type in the JSON string but got `%s`", jsonObj.get("VerifiedFileFormat").toString()));
      }
      if (jsonObj.get("FoundViruses") != null && !jsonObj.get("FoundViruses").isJsonNull()) {
        JsonArray jsonArrayfoundViruses = jsonObj.getAsJsonArray("FoundViruses");
        if (jsonArrayfoundViruses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("FoundViruses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `FoundViruses` to be an array in the JSON string but got `%s`", jsonObj.get("FoundViruses").toString()));
          }

          // validate the optional field `FoundViruses` (array)
          for (int i = 0; i < jsonArrayfoundViruses.size(); i++) {
            VirusFound.validateJsonElement(jsonArrayfoundViruses.get(i));
          };
        }
      }
      // validate the optional field `ContentInformation`
      if (jsonObj.get("ContentInformation") != null && !jsonObj.get("ContentInformation").isJsonNull()) {
        AdditionalAdvancedScanInformation.validateJsonElement(jsonObj.get("ContentInformation"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VirusScanAdvancedResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VirusScanAdvancedResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VirusScanAdvancedResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VirusScanAdvancedResult.class));

       return (TypeAdapter<T>) new TypeAdapter<VirusScanAdvancedResult>() {
           @Override
           public void write(JsonWriter out, VirusScanAdvancedResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VirusScanAdvancedResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VirusScanAdvancedResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VirusScanAdvancedResult
   * @throws IOException if the JSON string is invalid with respect to VirusScanAdvancedResult
   */
  public static VirusScanAdvancedResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VirusScanAdvancedResult.class);
  }

  /**
   * Convert an instance of VirusScanAdvancedResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

