/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.VirusFound;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of running a virus scan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T08:41:21.483351Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class VirusScanResult {
  public static final String SERIALIZED_NAME_CLEAN_RESULT = "CleanResult";
  @SerializedName(SERIALIZED_NAME_CLEAN_RESULT)
  @javax.annotation.Nullable
  private Boolean cleanResult;

  public static final String SERIALIZED_NAME_FOUND_VIRUSES = "FoundViruses";
  @SerializedName(SERIALIZED_NAME_FOUND_VIRUSES)
  @javax.annotation.Nullable
  private List<VirusFound> foundViruses = new ArrayList<>();

  public VirusScanResult() {
  }

  public VirusScanResult cleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
    return this;
  }

  /**
   * True if the scan contained no viruses, false otherwise
   * @return cleanResult
   */
  @javax.annotation.Nullable
  public Boolean getCleanResult() {
    return cleanResult;
  }

  public void setCleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
  }


  public VirusScanResult foundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
    return this;
  }

  public VirusScanResult addFoundVirusesItem(VirusFound foundVirusesItem) {
    if (this.foundViruses == null) {
      this.foundViruses = new ArrayList<>();
    }
    this.foundViruses.add(foundVirusesItem);
    return this;
  }

  /**
   * Array of viruses found, if any
   * @return foundViruses
   */
  @javax.annotation.Nullable
  public List<VirusFound> getFoundViruses() {
    return foundViruses;
  }

  public void setFoundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirusScanResult virusScanResult = (VirusScanResult) o;
    return Objects.equals(this.cleanResult, virusScanResult.cleanResult) &&
        Objects.equals(this.foundViruses, virusScanResult.foundViruses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanResult, foundViruses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirusScanResult {\n");
    sb.append("    cleanResult: ").append(toIndentedString(cleanResult)).append("\n");
    sb.append("    foundViruses: ").append(toIndentedString(foundViruses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CleanResult");
    openapiFields.add("FoundViruses");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VirusScanResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VirusScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VirusScanResult is not found in the empty JSON string", VirusScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VirusScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VirusScanResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("FoundViruses") != null && !jsonObj.get("FoundViruses").isJsonNull()) {
        JsonArray jsonArrayfoundViruses = jsonObj.getAsJsonArray("FoundViruses");
        if (jsonArrayfoundViruses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("FoundViruses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `FoundViruses` to be an array in the JSON string but got `%s`", jsonObj.get("FoundViruses").toString()));
          }

          // validate the optional field `FoundViruses` (array)
          for (int i = 0; i < jsonArrayfoundViruses.size(); i++) {
            VirusFound.validateJsonElement(jsonArrayfoundViruses.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VirusScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VirusScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VirusScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VirusScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<VirusScanResult>() {
           @Override
           public void write(JsonWriter out, VirusScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VirusScanResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VirusScanResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VirusScanResult
   * @throws IOException if the JSON string is invalid with respect to VirusScanResult
   */
  public static VirusScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VirusScanResult.class);
  }

  /**
   * Convert an instance of VirusScanResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

