/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.VirusFound;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of running a website scan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T23:59:36.607801Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class WebsiteScanResult {
  public static final String SERIALIZED_NAME_CLEAN_RESULT = "CleanResult";
  @SerializedName(SERIALIZED_NAME_CLEAN_RESULT)
  @javax.annotation.Nullable
  private Boolean cleanResult;

  /**
   * Type of threat returned; can be None, Malware, ForcedDownload or Phishing
   */
  @JsonAdapter(WebsiteThreatTypeEnum.Adapter.class)
  public enum WebsiteThreatTypeEnum {
    NONE("None"),
    
    MALWARE("Malware"),
    
    PHISHING("Phishing"),
    
    FORCED_DOWNLOAD("ForcedDownload"),
    
    UNABLE_TO_CONNECT("UnableToConnect");

    private String value;

    WebsiteThreatTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static WebsiteThreatTypeEnum fromValue(String value) {
      for (WebsiteThreatTypeEnum b : WebsiteThreatTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<WebsiteThreatTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final WebsiteThreatTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public WebsiteThreatTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return WebsiteThreatTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      WebsiteThreatTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_WEBSITE_THREAT_TYPE = "WebsiteThreatType";
  @SerializedName(SERIALIZED_NAME_WEBSITE_THREAT_TYPE)
  @javax.annotation.Nullable
  private WebsiteThreatTypeEnum websiteThreatType;

  public static final String SERIALIZED_NAME_FOUND_VIRUSES = "FoundViruses";
  @SerializedName(SERIALIZED_NAME_FOUND_VIRUSES)
  @javax.annotation.Nullable
  private List<VirusFound> foundViruses = new ArrayList<>();

  public static final String SERIALIZED_NAME_WEBSITE_HTTP_RESPONSE_CODE = "WebsiteHttpResponseCode";
  @SerializedName(SERIALIZED_NAME_WEBSITE_HTTP_RESPONSE_CODE)
  @javax.annotation.Nullable
  private Integer websiteHttpResponseCode;

  public WebsiteScanResult() {
  }

  public WebsiteScanResult cleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
    return this;
  }

  /**
   * True if the scan contained no threats, false otherwise
   * @return cleanResult
   */
  @javax.annotation.Nullable
  public Boolean getCleanResult() {
    return cleanResult;
  }

  public void setCleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
  }


  public WebsiteScanResult websiteThreatType(@javax.annotation.Nullable WebsiteThreatTypeEnum websiteThreatType) {
    this.websiteThreatType = websiteThreatType;
    return this;
  }

  /**
   * Type of threat returned; can be None, Malware, ForcedDownload or Phishing
   * @return websiteThreatType
   */
  @javax.annotation.Nullable
  public WebsiteThreatTypeEnum getWebsiteThreatType() {
    return websiteThreatType;
  }

  public void setWebsiteThreatType(@javax.annotation.Nullable WebsiteThreatTypeEnum websiteThreatType) {
    this.websiteThreatType = websiteThreatType;
  }


  public WebsiteScanResult foundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
    return this;
  }

  public WebsiteScanResult addFoundVirusesItem(VirusFound foundVirusesItem) {
    if (this.foundViruses == null) {
      this.foundViruses = new ArrayList<>();
    }
    this.foundViruses.add(foundVirusesItem);
    return this;
  }

  /**
   * Array of viruses found, if any
   * @return foundViruses
   */
  @javax.annotation.Nullable
  public List<VirusFound> getFoundViruses() {
    return foundViruses;
  }

  public void setFoundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
  }


  public WebsiteScanResult websiteHttpResponseCode(@javax.annotation.Nullable Integer websiteHttpResponseCode) {
    this.websiteHttpResponseCode = websiteHttpResponseCode;
    return this;
  }

  /**
   * The remote server URL HTTP reasponse code; useful for debugging issues with scanning; typically if the remote server returns a 200 or 300-series code this means a successful response, while a 400 or 500 series code would represent an error returned from the remote server for the provided URL.
   * @return websiteHttpResponseCode
   */
  @javax.annotation.Nullable
  public Integer getWebsiteHttpResponseCode() {
    return websiteHttpResponseCode;
  }

  public void setWebsiteHttpResponseCode(@javax.annotation.Nullable Integer websiteHttpResponseCode) {
    this.websiteHttpResponseCode = websiteHttpResponseCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebsiteScanResult websiteScanResult = (WebsiteScanResult) o;
    return Objects.equals(this.cleanResult, websiteScanResult.cleanResult) &&
        Objects.equals(this.websiteThreatType, websiteScanResult.websiteThreatType) &&
        Objects.equals(this.foundViruses, websiteScanResult.foundViruses) &&
        Objects.equals(this.websiteHttpResponseCode, websiteScanResult.websiteHttpResponseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanResult, websiteThreatType, foundViruses, websiteHttpResponseCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebsiteScanResult {\n");
    sb.append("    cleanResult: ").append(toIndentedString(cleanResult)).append("\n");
    sb.append("    websiteThreatType: ").append(toIndentedString(websiteThreatType)).append("\n");
    sb.append("    foundViruses: ").append(toIndentedString(foundViruses)).append("\n");
    sb.append("    websiteHttpResponseCode: ").append(toIndentedString(websiteHttpResponseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CleanResult");
    openapiFields.add("WebsiteThreatType");
    openapiFields.add("FoundViruses");
    openapiFields.add("WebsiteHttpResponseCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebsiteScanResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebsiteScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebsiteScanResult is not found in the empty JSON string", WebsiteScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebsiteScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebsiteScanResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("WebsiteThreatType") != null && !jsonObj.get("WebsiteThreatType").isJsonNull()) && !jsonObj.get("WebsiteThreatType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `WebsiteThreatType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("WebsiteThreatType").toString()));
      }
      // validate the optional field `WebsiteThreatType`
      if (jsonObj.get("WebsiteThreatType") != null && !jsonObj.get("WebsiteThreatType").isJsonNull()) {
        WebsiteThreatTypeEnum.validateJsonElement(jsonObj.get("WebsiteThreatType"));
      }
      if (jsonObj.get("FoundViruses") != null && !jsonObj.get("FoundViruses").isJsonNull()) {
        JsonArray jsonArrayfoundViruses = jsonObj.getAsJsonArray("FoundViruses");
        if (jsonArrayfoundViruses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("FoundViruses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `FoundViruses` to be an array in the JSON string but got `%s`", jsonObj.get("FoundViruses").toString()));
          }

          // validate the optional field `FoundViruses` (array)
          for (int i = 0; i < jsonArrayfoundViruses.size(); i++) {
            VirusFound.validateJsonElement(jsonArrayfoundViruses.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebsiteScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebsiteScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebsiteScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebsiteScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<WebsiteScanResult>() {
           @Override
           public void write(JsonWriter out, WebsiteScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebsiteScanResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebsiteScanResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebsiteScanResult
   * @throws IOException if the JSON string is invalid with respect to WebsiteScanResult
   */
  public static WebsiteScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebsiteScanResult.class);
  }

  /**
   * Convert an instance of WebsiteScanResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

