/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdditionalAdvancedScanInformation
 */
public class AdditionalAdvancedScanInformationTest {
    private final AdditionalAdvancedScanInformation model = new AdditionalAdvancedScanInformation();

    /**
     * Model tests for AdditionalAdvancedScanInformation
     */
    @Test
    public void testAdditionalAdvancedScanInformation() {
        // TODO: test AdditionalAdvancedScanInformation
    }

    /**
     * Test the property 'containsJSON'
     */
    @Test
    public void containsJSONTest() {
        // TODO: test containsJSON
    }

    /**
     * Test the property 'containsXML'
     */
    @Test
    public void containsXMLTest() {
        // TODO: test containsXML
    }

    /**
     * Test the property 'containsImage'
     */
    @Test
    public void containsImageTest() {
        // TODO: test containsImage
    }

    /**
     * Test the property 'hashSHA1'
     */
    @Test
    public void hashSHA1Test() {
        // TODO: test hashSHA1
    }

    /**
     * Test the property 'relevantSubfileName'
     */
    @Test
    public void relevantSubfileNameTest() {
        // TODO: test relevantSubfileName
    }

    /**
     * Test the property 'relevantSubfileHashSHA1'
     */
    @Test
    public void relevantSubfileHashSHA1Test() {
        // TODO: test relevantSubfileHashSHA1
    }

    /**
     * Test the property 'isAuthenticodeSigned'
     */
    @Test
    public void isAuthenticodeSignedTest() {
        // TODO: test isAuthenticodeSigned
    }

}
