/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScanCloudStorageBatchJobCreateResult
 */
public class ScanCloudStorageBatchJobCreateResultTest {
    private final ScanCloudStorageBatchJobCreateResult model = new ScanCloudStorageBatchJobCreateResult();

    /**
     * Model tests for ScanCloudStorageBatchJobCreateResult
     */
    @Test
    public void testScanCloudStorageBatchJobCreateResult() {
        // TODO: test ScanCloudStorageBatchJobCreateResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'asyncJobID'
     */
    @Test
    public void asyncJobIDTest() {
        // TODO: test asyncJobID
    }

}
