/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AdditionalAdvancedScanInformation;
import org.openapitools.client.model.VirusFound;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VirusScanAdvancedResult
 */
public class VirusScanAdvancedResultTest {
    private final VirusScanAdvancedResult model = new VirusScanAdvancedResult();

    /**
     * Model tests for VirusScanAdvancedResult
     */
    @Test
    public void testVirusScanAdvancedResult() {
        // TODO: test VirusScanAdvancedResult
    }

    /**
     * Test the property 'cleanResult'
     */
    @Test
    public void cleanResultTest() {
        // TODO: test cleanResult
    }

    /**
     * Test the property 'containsExecutable'
     */
    @Test
    public void containsExecutableTest() {
        // TODO: test containsExecutable
    }

    /**
     * Test the property 'containsInvalidFile'
     */
    @Test
    public void containsInvalidFileTest() {
        // TODO: test containsInvalidFile
    }

    /**
     * Test the property 'containsScript'
     */
    @Test
    public void containsScriptTest() {
        // TODO: test containsScript
    }

    /**
     * Test the property 'containsPasswordProtectedFile'
     */
    @Test
    public void containsPasswordProtectedFileTest() {
        // TODO: test containsPasswordProtectedFile
    }

    /**
     * Test the property 'containsRestrictedFileFormat'
     */
    @Test
    public void containsRestrictedFileFormatTest() {
        // TODO: test containsRestrictedFileFormat
    }

    /**
     * Test the property 'containsMacros'
     */
    @Test
    public void containsMacrosTest() {
        // TODO: test containsMacros
    }

    /**
     * Test the property 'containsXmlExternalEntities'
     */
    @Test
    public void containsXmlExternalEntitiesTest() {
        // TODO: test containsXmlExternalEntities
    }

    /**
     * Test the property 'containsInsecureDeserialization'
     */
    @Test
    public void containsInsecureDeserializationTest() {
        // TODO: test containsInsecureDeserialization
    }

    /**
     * Test the property 'containsHtml'
     */
    @Test
    public void containsHtmlTest() {
        // TODO: test containsHtml
    }

    /**
     * Test the property 'containsUnsafeArchive'
     */
    @Test
    public void containsUnsafeArchiveTest() {
        // TODO: test containsUnsafeArchive
    }

    /**
     * Test the property 'containsOleEmbeddedObject'
     */
    @Test
    public void containsOleEmbeddedObjectTest() {
        // TODO: test containsOleEmbeddedObject
    }

    /**
     * Test the property 'containsUnwantedAction'
     */
    @Test
    public void containsUnwantedActionTest() {
        // TODO: test containsUnwantedAction
    }

    /**
     * Test the property 'verifiedFileFormat'
     */
    @Test
    public void verifiedFileFormatTest() {
        // TODO: test verifiedFileFormat
    }

    /**
     * Test the property 'foundViruses'
     */
    @Test
    public void foundVirusesTest() {
        // TODO: test foundViruses
    }

    /**
     * Test the property 'contentInformation'
     */
    @Test
    public void contentInformationTest() {
        // TODO: test contentInformation
    }

}
