/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.VirusFound;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VirusScanResult
 */
public class VirusScanResultTest {
    private final VirusScanResult model = new VirusScanResult();

    /**
     * Model tests for VirusScanResult
     */
    @Test
    public void testVirusScanResult() {
        // TODO: test VirusScanResult
    }

    /**
     * Test the property 'cleanResult'
     */
    @Test
    public void cleanResultTest() {
        // TODO: test cleanResult
    }

    /**
     * Test the property 'foundViruses'
     */
    @Test
    public void foundVirusesTest() {
        // TODO: test foundViruses
    }

}
